### ISSUE TITLE
QUERY: License details

### ISSUE THREAD

**Issue by HaoZeke** [itapmd/imd#19]
Thanks for maintaining this fork on Github! I'm unclear on the licensing terms for the IMD code, as far as I can tell there's a GPL license on the fft, and no other mention. It would be great if this could be clarified.

The files have attribution but often long expired, eg:

```
* Copyright 1996-2008 Institute for Theoretical and Applied Physics,
* University of Stuttgart, D-70550 Stuttgart
```

**Comment by johroth** [comment]
The license is mention in the documentation. Actually the GPL license applies to the whole code. If you use IMD for syour work you should cite the publications mentioned in the documentation.
